export const users = [
    {
      username: "Daniyal_Murtaza",
      firstName: "Daniyal",
      lastName: "Murtaza",
      school: "Habib University",
      email: "sz06880@st.habib.edu.pk",
      profilePicture: "https://picsum.photos/id/400/300",
      classLevel: "Freshmen",
    },
    {
      username: "Ali_kamal",
      firstName: "Ali",
      lastName: "Kamal",
      school: "Stanford University",
      email: "Ali_Kamal@stanford.edu",
      profilePicture: "https://picsum.photos/id/238/300",
      classLevel: "Sophomore",
    },
    {
      username: "Zaid_zaidi",
      firstName: "Zaid",
      lastName: "Zaidi",
      school: "Harvard University",
      email: "Zaid_Zaidi@Harvard.edu",
      profilePicture: "https://picsum.photos/id/3/300",
      classLevel: "Freshmen",
    },
    {
      username: "jane_smith",
      firstName: "Jane",
      lastName: "Smith",
      school: "NED University",
      email: "jane_smith@ned.edu.pk",
      profilePicture: "https://picsum.photos/id/12/300",
      classLevel: "Junior",
    },
    {
      username: "Zain_kazmi",
      firstName: "Zain",
      lastName: "Kazmi",
      school: "Fast University",
      email: "Zain_Kazmi@fast.edu.pk",
      profilePicture: "https://picsum.photos/id/1000/300",
      classLevel: "Senior",
    },
  ];
  